# Generated by Django 4.2 on 2023-04-28 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=12)),
                ('emergency_contact', models.CharField(max_length=100)),
                ('emergency_number', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.CharField(max_length=2)),
                ('number', models.IntegerField()),
                ('tenant', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.userprofile')),
            ],
        ),
    ]
