# Generated by Django 4.2 on 2023-04-28 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='tenant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.userprofile'),
        ),
    ]
