# Generated by Django 4.2 on 2023-04-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_apartment_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='num_rooms',
            field=models.IntegerField(choices=[(1, 'One Bedroom'), (2, 'Two Bedroom'), (3, 'Three Bedroom')], default=1),
        ),
    ]
