# Generated by Django 4.2 on 2023-05-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_maintenancerequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_property_manager',
            field=models.BooleanField(default=False),
        ),
    ]
